### ISSUE TITLE
複習 Git 與 Review 操作

### ISSUE THREAD

**Issue by Gaduo** [TCU-MI/TrainingXiuan#3]
複習
===

上傳
===
1. 收到作業或是任務後要先建立一個 branch，接著才可以開始修改程式碼。  
`$ git checkout -b task-1`
1. 每修改一小段之後，需要 commit 。
 - 每一個 commit 都要有意義。
 - commit message 需要能表現該 commit 的意義
 - commit 之間保持「小步前進」的步調
 - [工作流程與作業規範](https://github.com/TCU-MI/Training)
1. 寫好程式碼後需要他人審查，則先推送到  github 的 origin 中。  
`$ git push origin task-1`
1. 在利用 Github 的 Pull Request 指令給 Gaduo/TrainingXiuan

同步 TCU-MI/Repo
============
結束一循環的任務後，local master 則需要從 TCUMI/TrainingXiuan master 上同步最新的資料。

1. 先切換到 master 分支。  
`$ git checkout master`
1. 將 TCUMI/TrainingXiuan master 同步到 local/TrainingXiuan master。  
`$ git pull upstream master`
1. 再將 local/TrainingXiuan master 推送到 origin master
`$ git push origin master`

TAKS
====
請將以下問題說明寫在專案目錄中的 `doc/task-git.md` 中

1. 請說明 `$ git status` 的用途
1. 請說明 `$ git log` 的用途以及參數 `--oneline`、`-n 3` 的意思
1. 請問要恢復到某一次的 commit 需要一個 commit hashcode，此 hashcode 可以從哪裡查詢到。
復原指令：`$ git reset <hashcode>`
1. remote server （遠端伺服器）有 origin 與 upstream 分別代表什麼意思？

**Comment by Ann1213** [comment]
1. `$ git status`：列出目前狀態，告知是否有未更新的檔案
2. `$ git log`：查看歷史紀錄        `--oneline`：一行一行印出       `-n 3`：只要印3個紀錄
3. `hashcode`：從`$ git log`裡可以看到所有的代碼
4. `origin`：指向自己存在local的github      `upstream`：遠端指向自己的github
